name: Release
on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and install dependencies
        uses: ./.github/actions/setup-node-and-install-dependencies
        with:
          main-branch-name: master
          node-version: '16.15.1'
          registry-url: https://npm.pkg.github.com/

      - name: Version
        run: pnpm exec nx affected -t version --base=latest
        shell: bash

      - name: Tag latest
        run: |
          git tag -f latest
          git push origin latest --force
        shell: bash
